/**
 * Shim-facing IPC API (application layer, pure).
 *
 * Security model for local shim requests: a shared secret token (generated by
 * the daemon, written to a user-only file) guards every op. Agent-neutral —
 * this handler never learns whether the caller is Claude Code, Codex, or other.
 */
import { timingSafeEqual } from 'node:crypto';
import type { State } from './state.js';
import type { ApiHandler, ApiRequest, ApiResponse } from './http.js';
import type { WebRequest } from '../shared/types.js';

export interface IpcApiConfig {
  token: string;
  /** default long-poll timeout for watch, ms. */
  watchTimeoutMs?: number;
}

const DEFAULT_WATCH_TIMEOUT_MS = 25_000;

const TOKEN_HEADER = 'x-web-picker-token';

function json(status: number, body: unknown): ApiResponse {
  return { status, body };
}

/** Constant-time token comparison to avoid leaking length/prefix via timing. */
function tokenMatches(provided: string | undefined, expected: string): boolean {
  if (!provided) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

function pendingRequests(state: State): WebRequest[] {
  return state.list().filter((r) => r.status === 'pending');
}

function ownerConflict(state: State, sessionId: unknown): ApiResponse | null {
  state.sweep();
  if (typeof sessionId === 'string' && sessionId.length > 0 && state.activeSessionId === sessionId) {
    return null;
  }
  return json(409, { ok: false, activeSessionId: state.activeSessionId });
}

export function createIpcApi(state: State, config: IpcApiConfig): ApiHandler {
  const watchTimeoutMs = config.watchTimeoutMs ?? DEFAULT_WATCH_TIMEOUT_MS;

  return (req) => {
    if (req.path !== '/ipc') return json(404, { error: 'not found' });
    if (!tokenMatches(req.headers[TOKEN_HEADER], config.token)) {
      return json(401, { error: 'unauthorized' });
    }

    const body = (req.body ?? {}) as Record<string, unknown>;
    const op = body.op as string | undefined;

    switch (op) {
      case 'register': {
        const session = state.register(String(body.sessionId), String(body.label ?? body.sessionId));
        return json(200, { ok: true, session });
      }
      case 'heartbeat': {
        state.heartbeat(String(body.sessionId));
        return json(200, { ok: true });
      }
      case 'claim': {
        const ok = state.claim(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId, pending: state.list().filter((r) => r.status === 'pending').length });
      }
      case 'take_over': {
        const ok = state.takeOver(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId });
      }
      case 'release': {
        const ok = state.release(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId });
      }
      case 'list': {
        const conflict = ownerConflict(state, body.sessionId);
        if (conflict) return conflict;
        return json(200, { ok: true, requests: state.list() });
      }
      case 'get': {
        const conflict = ownerConflict(state, body.sessionId);
        if (conflict) return conflict;
        return json(200, { ok: true, request: state.get(String(body.id)) ?? null });
      }
      case 'pull': {
        const conflict = ownerConflict(state, body.sessionId);
        if (conflict) return conflict;
        const requests = state.pull();
        return json(200, { ok: true, requests });
      }
      case 'watch': {
        const conflict = ownerConflict(state, body.sessionId);
        if (conflict) return conflict;
        const now = pendingRequests(state);
        if (now.length > 0) return json(200, { ok: true, requests: now });
        const timeout = typeof body.timeoutMs === 'number' ? body.timeoutMs : watchTimeoutMs;
        return new Promise<ApiResponse>((resolve) => {
          let settled = false;
          const finish = (requests: WebRequest[]) => {
            if (settled) return;
            settled = true;
            clearTimeout(timer);
            unsub();
            const conflict = ownerConflict(state, body.sessionId);
            if (conflict) {
              resolve(conflict);
              return;
            }
            resolve(json(200, { ok: true, requests }));
          };
          const unsub = state.subscribe(() => finish(pendingRequests(state)));
          const timer = setTimeout(() => finish([]), timeout);
          // don't let a pending watch keep the process alive
          if (typeof (timer as { unref?: () => void }).unref === 'function') {
            (timer as { unref: () => void }).unref();
          }
        });
      }
      case 'resolve': {
        const conflict = ownerConflict(state, body.sessionId);
        if (conflict) return conflict;
        const ok = state.resolve(String(body.id));
        return json(200, { ok });
      }
      default:
        return json(400, { error: `unknown op: ${op ?? '(none)'}` });
    }
  };
}
