/**
 * Shim-facing IPC API (application layer, pure).
 *
 * Security model for local shim requests: a shared secret token (generated by
 * the daemon, written to a user-only file) guards every op. Agent-neutral —
 * this handler never learns whether the caller is Claude Code, Codex, or other.
 */
import { timingSafeEqual } from 'node:crypto';
import type { State } from './state.js';
import type { ApiHandler, ApiRequest, ApiResponse } from './http.js';

export interface IpcApiConfig {
  token: string;
}

const TOKEN_HEADER = 'x-web-picker-token';

function json(status: number, body: unknown): ApiResponse {
  return { status, body };
}

/** Constant-time token comparison to avoid leaking length/prefix via timing. */
function tokenMatches(provided: string | undefined, expected: string): boolean {
  if (!provided) return false;
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

export function createIpcApi(state: State, config: IpcApiConfig): ApiHandler {
  return (req) => {
    if (req.path !== '/ipc') return json(404, { error: 'not found' });
    if (!tokenMatches(req.headers[TOKEN_HEADER], config.token)) {
      return json(401, { error: 'unauthorized' });
    }

    const body = (req.body ?? {}) as Record<string, unknown>;
    const op = body.op as string | undefined;

    switch (op) {
      case 'register': {
        const session = state.register(String(body.sessionId), String(body.label ?? body.sessionId));
        return json(200, { ok: true, session });
      }
      case 'heartbeat': {
        state.heartbeat(String(body.sessionId));
        return json(200, { ok: true });
      }
      case 'claim': {
        const ok = state.claim(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId, pending: state.list().filter((r) => r.status === 'pending').length });
      }
      case 'take_over': {
        const ok = state.takeOver(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId });
      }
      case 'release': {
        const ok = state.release(String(body.sessionId));
        return json(200, { ok, activeSessionId: state.activeSessionId });
      }
      case 'pull': {
        const requests = state.pull();
        return json(200, { ok: true, requests });
      }
      case 'resolve': {
        const ok = state.resolve(String(body.id));
        return json(200, { ok });
      }
      default:
        return json(400, { error: `unknown op: ${op ?? '(none)'}` });
    }
  };
}
